version: '3.8'

services:
  app:
    build: .
    container_name: final-project-app
    ports:
      - "8080:8000"
    env_file:
      - .env
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge