version: '3.8'

services:
  app:
    build: .
    container_name: final-project-app-dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge